CPPUNIT_PATH = /home/vipulsharma/cppunit-cvs-repo-archive

btest: btest.o crash.o bruch.o
	gcc -o btest btest.o crashed.  o break.o -L $ {CPPUNIT_PATH} / lib -lstdc ++ -lcppunit -ldl

break.o : break.cc break.h
	gcc -c break.cc

break_test.o : break_test.cc
	gcc -c break_test.cc -I $ {CPPUNIT_PATH} / include

btest.o : btest.cc
	gcc -c btest.cc -I $ {CPPUNIT_PATH} / include